<?php /** @var Untitled_AppliedPatches_Block_Patches $this */ ?>
<?php if ($this->hasPatches()): ?>
    <div id="untitled-appliedpatches">
        <b><?php echo $this->__('Applied Patches'); ?>: </b>
        <?php foreach ($this->getAppliedPatches() as $patch): ?>
            <a href="#"
                data-patch-name="<?php echo $patch['name']; ?>"
                data-patch-applied-date="<?php echo $patch['appliedOnDate']; ?>">
                <?php echo $patch['name']; ?>
            </a><?php echo $this->getIsLast($patch); ?>
        <?php endforeach; ?>
    </div>
    <script>
        document.observe("dom:loaded", function() {
            $('untitled-appliedpatches').observe('click', function(event) {
                var el = event.findElement('a');
                if(el) {
                    var patchName = el.readAttribute('data-patch-name') || '',
                        patchDateRevertedOn = el.readAttribute('data-patch-applied-date') || '';
                    new UntitledAppliedPatches.dialog(patchName, patchDateRevertedOn).openDialogWindow();
                }
            });
        });
    </script>
<?php endif; ?>